import { createFileRoute, Link } from "@tanstack/react-router";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { Section } from "@/components/section";
import { breadcrumbSchema, createSeo, jsonLd } from "@/lib/seo";

const seo = createSeo({ title: "Disclaimer | Progateway Consultancy", description: "Important limitations and disclaimers for Progateway Consultancy services, website information, loans, tax, investment, insurance and certifications.", path: "/disclaimer" });
export const Route = createFileRoute("/disclaimer")({ head: () => ({ ...seo, scripts: [jsonLd(breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Disclaimer", path: "/disclaimer" }]))] }), component: DisclaimerPage });

function DisclaimerPage() {
  return <><section className="border-b border-border bg-surface"><div className="container-page py-12 md:py-16"><Breadcrumbs items={[{ label: "Home", to: "/" }, { label: "Disclaimer" }]} /><h1 className="mt-6 text-4xl font-extrabold md:text-5xl">Disclaimer</h1><p className="mt-4 max-w-3xl text-muted-foreground">Last updated: 15 July 2026</p></div></section><Section><article className="mx-auto max-w-3xl space-y-10 text-base leading-8 text-foreground/85"><section><h2 className="text-2xl font-bold">General information</h2><p className="mt-3">Website content is general information and does not create a professional engagement by itself. Requirements, forms, fees, laws, due dates and portal processes can change. Verify current information with the relevant official authority.</p></section><section><h2 className="text-2xl font-bold">No approval or outcome guarantee</h2><p className="mt-3">Progateway Consultancy assists with understanding requirements, preparing documents, applications and follow-up. Final decisions are made by government authorities, banks, NBFCs, insurers, certification bodies and other independent organisations.</p></section><section><h2 className="text-2xl font-bold">Tax, legal and regulatory matters</h2><p className="mt-3">Content does not replace advice from a chartered accountant, advocate, company secretary, tax practitioner or other qualified professional where such advice is required by law or appropriate to the facts.</p></section><section><h2 className="text-2xl font-bold">Loans, investment and insurance</h2><p className="mt-3">Loan sanction, pricing and disbursement are subject to lender policy. Investment returns may be market-linked and are not guaranteed. Insurance coverage is governed by the official policy wording, underwriting, exclusions and insurer decision.</p></section><section><h2 className="text-2xl font-bold">External links</h2><p className="mt-3">Links to government, regulatory and third-party websites are provided for convenience. Progateway does not control their availability, accuracy or security.</p></section><p>Read the <Link to="/privacy" className="font-semibold text-primary">Privacy Policy</Link>, <Link to="/terms" className="font-semibold text-primary">Terms of Service</Link> and <Link to="/refund-cancellation" className="font-semibold text-primary">Refund & Cancellation Policy</Link>.</p></article></Section></>;
}
