import { createFileRoute, Link } from "@tanstack/react-router";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { Section } from "@/components/section";
import { breadcrumbSchema, createSeo, jsonLd } from "@/lib/seo";

const seo = createSeo({ title: "Editorial Policy | Progateway Consultancy Resources", description: "How Progateway Consultancy creates, reviews, updates and corrects educational content about tax, registrations, loans and finance.", path: "/editorial-policy" });
export const Route = createFileRoute("/editorial-policy")({ head: () => ({ ...seo, scripts: [jsonLd(breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Editorial Policy", path: "/editorial-policy" }]))] }), component: EditorialPolicyPage });

function EditorialPolicyPage() { return <><section className="border-b border-border bg-surface"><div className="container-page py-12 md:py-16"><Breadcrumbs items={[{ label: "Home", to: "/" }, { label: "Editorial Policy" }]} /><h1 className="mt-6 text-4xl font-extrabold md:text-5xl">Editorial Policy</h1><p className="mt-4 text-muted-foreground">Last updated: 15 July 2026</p></div></section><Section><article className="mx-auto max-w-3xl space-y-10 text-base leading-8 text-foreground/85"><section><h2 className="text-2xl font-bold">Purpose</h2><p className="mt-3">The resource centre explains common service processes in plain language so readers can prepare better questions and documents. It is not designed to replace case-specific professional advice.</p></section><section><h2 className="text-2xl font-bold">Sources</h2><p className="mt-3">Articles prioritise official government, regulator and statutory portal sources. Source links are shown visibly. Third-party claims are not used as the sole authority for legal or regulatory requirements.</p></section><section><h2 className="text-2xl font-bold">Review and updates</h2><p className="mt-3">Each article identifies an author, review attribution and updated date. Content should be reviewed when a material portal, form, law or process changes, and at least periodically for broken links or outdated statements.</p></section><section><h2 className="text-2xl font-bold">Accuracy and corrections</h2><p className="mt-3">Unsupported guarantees, invented credentials, fake statistics and copied competitor content are prohibited. Material errors should be corrected promptly and the updated date changed where appropriate.</p></section><section><h2 className="text-2xl font-bold">Commercial transparency</h2><p className="mt-3">Articles may link to relevant Progateway services. These links do not change the obligation to present balanced limitations, official sources and the fact that external authorities make final decisions.</p></section><p>Browse the <Link to="/resources" className="font-semibold text-primary">resource centre</Link> or report a correction through the <Link to="/contact" className="font-semibold text-primary">contact page</Link>.</p></article></Section></>; }
