import { createFileRoute, Link } from "@tanstack/react-router";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { Section } from "@/components/section";
import { breadcrumbSchema, createSeo, jsonLd } from "@/lib/seo";

const seo = createSeo({ title: "Refund & Cancellation Policy | Progateway Consultancy", description: "Understand Progateway Consultancy's service cancellation, professional fee, government fee and refund review policy.", path: "/refund-cancellation" });
export const Route = createFileRoute("/refund-cancellation")({ head: () => ({ ...seo, scripts: [jsonLd(breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Refund and Cancellation", path: "/refund-cancellation" }]))] }), component: RefundPage });

function RefundPage() { return <><section className="border-b border-border bg-surface"><div className="container-page py-12 md:py-16"><Breadcrumbs items={[{ label: "Home", to: "/" }, { label: "Refund & Cancellation" }]} /><h1 className="mt-6 text-4xl font-extrabold md:text-5xl">Refund & Cancellation Policy</h1><p className="mt-4 text-muted-foreground">Last updated: 15 July 2026</p></div></section><Section><article className="mx-auto max-w-3xl space-y-10 text-base leading-8 text-foreground/85"><section><h2 className="text-2xl font-bold">Before work begins</h2><p className="mt-3">The service scope, professional fee and known government or third-party charges should be confirmed before payment. Ask questions before authorising filing, document preparation or third-party payment.</p></section><section><h2 className="text-2xl font-bold">Cancellation request</h2><p className="mt-3">A cancellation request should be made promptly by phone, email or WhatsApp. The review will consider whether consultation, document review, drafting, filing, portal work, payment or follow-up has already occurred.</p></section><section><h2 className="text-2xl font-bold">Professional fees</h2><p className="mt-3">Any refund of professional fees is assessed against work already completed and committed costs. Completed consultation, drafting, verification or submission work may be non-refundable to the extent already performed.</p></section><section><h2 className="text-2xl font-bold">Government and third-party charges</h2><p className="mt-3">Government fees, stamp duty, portal payments, certification charges, lender charges, insurer premiums and other third-party amounts are subject to the refund rules of the receiving organisation and may not be recoverable after payment.</p></section><section><h2 className="text-2xl font-bold">No refund based solely on an external rejection</h2><p className="mt-3">An authority, lender, insurer or certification body may reject, query or delay an application. Where Progateway has performed the agreed professional work, an external decision alone does not automatically create a refund entitlement.</p></section><p>For a written review, contact Progateway through the details on the <Link to="/contact" className="font-semibold text-primary">contact page</Link>.</p></article></Section></>; }
